java_import 'java.util.concurrent.atomic.AtomicInteger'

require_relative '../../java_lib/quickfixj-all-1.5.3'
require_relative '../../java_lib/slf4j-api-1.7.7.jar'
require_relative '../../java_lib/slf4j-jdk14-1.7.7.jar'
require_relative '../../java_lib/mina-core-1.1.0.jar'

java_import 'quickfix.fix43.MarketDataIncrementalRefresh'
java_import 'quickfix.fix43.MessageCracker'

java_import 'quickfix.field.OrigClOrdID'
java_import 'quickfix.field.ClOrdID'
java_import 'quickfix.field.Side'
java_import 'quickfix.field.TransactTime'
java_import 'quickfix.field.OrdType'
java_import 'quickfix.field.HandlInst'
java_import 'quickfix.field.ApplVerID'
java_import 'quickfix.field.MDReqID'
java_import 'quickfix.field.MDUpdateAction'
java_import 'quickfix.field.MDEntryType'
java_import 'quickfix.field.MDEntryPx'
java_import 'quickfix.field.MDEntrySize'
java_import 'quickfix.field.MDEntryRefID'
java_import 'quickfix.field.OrderID'
java_import 'quickfix.field.SenderCompID'
java_import 'quickfix.field.TargetCompID'
java_import 'quickfix.field.MDEntryDate'
java_import 'quickfix.field.MDEntryTime'
java_import 'quickfix.field.NoMDEntries'

java_import 'quickfix.StringField'
java_import 'quickfix.SessionID'
java_import 'quickfix.SessionSettings'
java_import 'quickfix.MemoryStoreFactory'
java_import 'quickfix.ScreenLogFactory'
java_import 'quickfix.DefaultMessageFactory'
java_import 'quickfix.SocketInitiator'
java_import 'quickfix.SocketAcceptor'
java_import 'quickfix.Session'
java_import 'quickfix.DataDictionary'
java_import 'quickfix.DefaultMessageFactory'
java_import 'quickfix.DefaultDataDictionaryProvider'
java_import 'quickfix.MessageUtils'
java_import 'quickfix.MessageStoreFactory'
java_import 'quickfix.MessageStore'
